version: "3.8"

services:

  postgres:

    image: postgres:16

    container_name: nova-postgres


    restart: always


    environment:

      POSTGRES_USER: nova_user

      POSTGRES_PASSWORD: nova_password

      POSTGRES_DB: nova_database


    ports:

      - "5432:5432"


    volumes:

      - postgres_data:/var/lib/postgresql/data



volumes:

  postgres_data: